### ISSUE TITLE
no  Phass 

### ISSUE THREAD

**Issue by DONGYUSEN** [isce-framework/fringe#39]
Traceback (most recent call last):
  File "/Users/ysdong/Software/Fringe/install/bin/unwrap_fringe.py", line 126, in <module>
    unwrap_phass(inps, length, width)
  File "/Users/ysdong/Software/Fringe/install/bin/unwrap_fringe.py", line 35, in unwrap_phass
    import Phass
ModuleNotFoundError: No module named 'Phass'

**Comment by yunjunz** [comment]
A similar issue has been posted before, I recommend you to search and check that.
