### ISSUE TITLE
Processing imageMath.py error

### ISSUE THREAD

**Issue by SiriusXCH0103** [isce-framework/fringe#57]
I followed the steps in the "workflow.md", an error occurred when I do the "imageMath.py" step.
The error message is as follows：

```
This is the Open Source version of ISCE.
Some of the workflows depend on a separate licensed package.
To obtain the licensed package, please make a request for ISCE
through the website: https://download.jpl.nasa.gov/ops/request/index.cfm.
Alternatively, if you are a member, or can become a member of WinSAR
you may be able to obtain access to a version of the licensed sofware at
https://winsar.unavco.org/software/isce
args:  Namespace(debug=False, dtype='byte', equation='a<0.4', hh=None, noxml=False, out='ampDispersion/ps_pixel', scheme='BSQ')
files:  ['--a=ampDispersion/ampdispersion']
Traceback (most recent call last):
  File "/home/xch/isce2/install/isce/components/isceobj/Util/ImageUtil/ImageLib.py", line 465, in mmapFromISCE
    img, dataName, metaName = loadImage(fname)
  File "/home/xch/isce2/install/isce/components/isceobj/Util/ImageUtil/ImageLib.py", line 416, in loadImage
    prop,fac,misc = parser.parse(metaName)
  File "/home/xch/isce2/install/isce/components/iscesys/Parsers/XmlParser.py", line 41, in parse
    root = ET.parse(filename)
  File "/home/xch/anaconda3/lib/python3.8/xml/etree/ElementTree.py", line 1202, in parse
    tree.parse(source, parser)
  File "/home/xch/anaconda3/lib/python3.8/xml/etree/ElementTree.py", line 584, in parse
    source = open(source, "rb")
FileNotFoundError: [Errno 2] No such file or directory: 'ampDispersion/ampdispersion.xml'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/xch/isce2/install/isce/components/isceobj/Util/ImageUtil/ImageLib.py", line 469, in mmapFromISCE
    img = loadGDALImage(fname)
  File "/home/xch/isce2/install/isce/components/isceobj/Util/ImageUtil/ImageLib.py", line 452, in loadGDALImage
    img.dataType = gdal.GetDataTypeByName(bnd.DataType)
  File "/home/xch/anaconda3/lib/python3.8/site-packages/osgeo/gdal.py", line 3199, in GetDataTypeByName
    return _gdal.GetDataTypeByName(*args)
TypeError: in method 'GetDataTypeByName', argument 1 of type 'char const *'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/xch/isce2/install/isce/applications/imageMath.py", line 451, in <module>
    main(args, files)
  File "/home/xch/isce2/install/isce/applications/imageMath.py", line 334, in main
    fmap = IML.mmapFromISCE(fstr, logger)
  File "/home/xch/isce2/install/isce/components/isceobj/Util/ImageUtil/ImageLib.py", line 473, in mmapFromISCE
```

I checked the "ampDispersion" dir, there are no any ".xml" files generated in the last step. 
Then I have redone 3 times, there wes always the same error.
How to solve this problem?

**Comment by stoormgeo** [comment]
Try gdal2isce_xml.py from isce2 package to make xml for mean and ampdispertion files.

**Comment by SiriusXCH0103** [comment]
> Try gdal2isce_xml.py from isce2 package to make xml for mean and ampdispertion files.

Thanks, very much!
